services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/backend/chroma_db
      - storage_data:/backend/storage
    environment:
      ENVIRONMENT: prod
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  chromadb_data:
    driver: local
  storage_data:
    driver: local