services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/backend/chroma_db
      - storage_data:/backend/storage
    environment:
      ENVIRONMENT: prod

volumes:
  chromadb_data:
    driver: local
  storage_data:
    driver: local